### ISSUE TITLE
Can't resolve '@pbj/live.js' after installing using npm | yarn

### ISSUE THREAD

**Issue by Sayyamabbasi786** [pbj-apps/live.js#2]
**Description**

I am looking to add live shopping feature into my React web app. After installing the package It still cannot able to resolve '@pbj/live.js'.

**Seps to reproduce**

#1 npx creat-react-app
#2 npm install @pbj/live.js
#3 import Live from '@pbj/live.js'; 

#Screenshot 

![Screenshot 2022-02-05 at 4 12 34 PM](https://user-images.githubusercontent.com/51042196/152639707-cbd514fb-8c1c-4ffa-a57c-d677393e0877.png)
![Screenshot 2022-02-05 at 4 13 10 PM](https://user-images.githubusercontent.com/51042196/152639729-ef09d4f6-52bb-47db-a3d9-5310966890ef.png)

## Versions

![Screenshot 2022-02-05 at 4 14 24 PM](https://user-images.githubusercontent.com/51042196/152639755-d6d3ed76-6f2a-45de-bbb1-8717df39e525.png)

**Comment by vikalpj** [comment]
@Sayyamabbasi786 This should be resolved in version v0.0.10

**Comment by Sayyamabbasi786** [comment]
ok will check it out
